import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'home',
    'what-is-acm',
    'quickstart',
    'core-concepts',
    'how-acm-works',
    'common-uses',
    'full-pipeline',
    'glossary',
    {
      type: 'category',
      label: 'Help',
      link: {type: 'doc', id: 'help/README'},
      items: [{type: 'autogenerated', dirName: 'help'}],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: [{type: 'autogenerated', dirName: 'users'}],
    },
    {
      type: 'category',
      label: 'Admin Guides',
      items: [{type: 'autogenerated', dirName: 'admins'}],
    },
    {
      type: 'category',
      label: 'Developer Guides',
      items: [{type: 'autogenerated', dirName: 'devs'}],
    },
    {
      type: 'category',
      label: 'Frontend Deep Dive',
      link: {type: 'doc', id: 'frontend/README'},
      items: [{type: 'autogenerated', dirName: 'frontend'}],
    },
    {
      type: 'category',
      label: 'Reference and Policy',
      items: ['LAWS', 'auth-security-report', 'DOCUSAURUS-GITHUB-PAGES-PLAN'],
    },
  ],
};

export default sidebars;
